HR-System/HR-System/Controllers/AuthController.cs
using HR_System.Models.DTOs;
using HR_System.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HR_System.Controllers
{
    public enum UserRole
    {
        User,
        HR
    }
    public class AuthController : Controller
    {
        private IUserService userService;
        
        public AuthController(IUserService service)
        {
            userService = service; ;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<UserDto>> Signup(RegisterUserDto data)
        {
            if (data.Roles == null || !data.Roles.Any() || data.Roles.Any(role => !Enum.TryParse(role, out UserRole userRole) || !Enum.IsDefined(typeof(UserRole), userRole)))
            {
                ModelState.AddModelError(nameof(data.Roles), "Invalid role selected.");
                return View();
            }

            var user = await userService.Register(data, data.Roles, ModelState);

            if (ModelState.IsValid)
            {
                return Redirect("/");
            }
            return View();
        }


        //[HttpPost]
        //public async Task<ActionResult<UserDto>> Signup(RegisterUserDto data)
        //{
        //    var user = await userService.Register(data, this.ModelState);

        //    if (ModelState.IsValid)
        //    {
        //        return Redirect("/");
        //    }
        //    return View();
        //}

        [HttpPost]
        public async Task<ActionResult<UserDto>> Authenticate(LoginData loginData)
        {

            var user = await userService.Authenticate(loginData.Username, loginData.Password);

            if (user == null)
            {
                this.ModelState.AddModelError("InvalidLogin", "Invalid login attempt");

                return RedirectToAction("Index");
            }

            //return RedirectToAction("Index" , "Auth");
            return Redirect("/");
        }

        public async Task<IActionResult> Logout()
        {
            await userService.Logout();
            return Redirect("/");
        }

    }
}

HR-System/HR-System/Controllers/EmployeeController.cs
using HR_System.Models;
using HR_System.Models.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HR_System.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee _employee;
        private readonly IConfiguration _configuration;
        public EmployeeController(IEmployee employee, IConfiguration configuration)
        {
            _employee = employee;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string searchTerm)
        {
            List<Employee> employees = await _employee.GetAllEmployees();
            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                employees = employees.Where(e => e.Name.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            return View(employees);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Employee employee, IFormFile file)
        {
            ModelState.Remove("file");

            if (!ModelState.IsValid)
            {
                return View(employee);
            }

            await _employee.PostEmployee(employee, file);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var empDetails = await _employee.GetEmployeeById(id);
            return View(empDetails);
        }

        public async Task<IActionResult> Details(int id)
        {
            var empDetails = await _employee.GetEmployeeById(id);
            return View(empDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Employee employee, IFormFile file)
        {
            ModelState.Remove("file");

            //if (!ModelState.IsValid)
            //{
            //    return View(employee);
            //}
            await _employee.UpdateEmployee(id, employee, file);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var empDetails = await _employee.GetEmployeeById(id);
            return View(empDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteEmployee(int id)
        {
            var empDetails = await _employee.GetEmployeeById(id);
            await _employee.DeleteEmployee(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HR-System/HR-System/Controllers/PositionController.cs
using HR_System.Models;
using HR_System.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HR_System.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPosition _position;

        public PositionController(IPosition position)
        {
            _position = position;
        }
        public async Task<IActionResult> Index()
        {
            var positions = await _position.GetAllPositions();
            return View(positions);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Position position)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(position);
            //}

            await _position.PostPosition(position);
            return RedirectToAction("Index", "Employee");
        }
    }
}

HR-System/HR-System/Controllers/SalaryController.cs
using HR_System.Models;
using HR_System.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HR_System.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ISalary _salary;
        public SalaryController(ISalary salary)
        {
            _salary = salary;
        }
        public async Task<IActionResult> Index()
        {
            var salaries = await _salary.GetAllSalaries();
            return View(salaries);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Salary salary)
        {
            if (!ModelState.IsValid)
            {
                return View(salary);
            }

            await _salary.PostSalary(salary);
            return RedirectToAction(nameof(Index));
        }
    }
}

HR-System/HR-System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR_System</title>
    <!-- ------------------------------------------------------------------------------- -->
    <!-- bootswatch CDN for the main style -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://bootswatch.com/5/darkly/bootstrap.min.css">
    <!-- ------------------------------------------------------------------------------  -->
@*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HR_System.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR_System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Logout", "Auth")">/ Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Auth")">sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Signup", "Auth")">Register</a>
                            </li>
                        } *@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Manage Employees</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin Actions
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Index", "Admin")">Admin Dashboard</a>
                                <a class="dropdown-item" href="@Url.Action("PendingUsers", "Admin")">Pending Users</a>
                                <a class="dropdown-item" href="@Url.Action("ClaimAdmin", "Admin")">Claim Admin privileges</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                HR Actions
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Create", "Salary")">Add Salary</a>
                                <a class="dropdown-item" href="@Url.Action("Create", "Department")">Add Department</a>
                                <a class="dropdown-item" href="@Url.Action("Create", "Position")">Add Position</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Salary")">Salaries</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Department")">Departments</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Position")">Positions</a>

                            </div>
                        </li>

                    </ul>
                    <div style="padding-right: 100px;">
                        <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                    <a class="nav-link" style="font-weight: bold;">@User.Identity.Name</a>
                            </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="font-weight: bold;" href="@Url.Action("Logout", "Auth")">/ Logout</a>
                            </li>
                        }
                        else
                        {
                                <li class="nav-item">
                                    <a class="nav-link" style="font-weight: bold;" href="@Url.Action("Index", "Auth")">sign in</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link" style="font-weight: bold;" href="@Url.Action("Signup", "Auth")">Register</a>
                            </li>
                        }
                    </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HR_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>